### ISSUE TITLE
Add requirements.txt

### ISSUE THREAD

**Issue by Viddesh1** [Viddesh1/RL#24]
Adding the requirements.txt file will be very help for installation of the necessary packages and any major dependencies for the project.

Requirement file should contain below packages one major dependencies of pygame:-

- [ ] requirements.txt

numpy==1.23.5
gym==0.24.0
pygame==2.3.0

**Comment by Project-Xenith** [comment]
is this issue still open?

**Comment by Viddesh1** [comment]
Hi @Project-Xenith ,

Thanks for your fast comment and your kind attention on this project and issue.
Yes, The Issue is still open.

Let me check with @SandhiyaAcharya if She would like to work on this github issue. As it was her Idea to add a requirement.txt file in project.
We will communicate with you regarding this issue.

If you want you can work on this issue:- https://github.com/Viddesh1/RL/issues/25

Adding @shruti-madhav @Ankita01K For visibility.

Thanks!
Viddesh
